services:
  - type: web
    name: attendance-flask
    env: python
    plan: free
    region: oregon
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    autoDeploy: true
